apiVersion: v1
kind: Service
metadata:
  labels:
    app: neural-corp3
  name: neural-corp3
  namespace: default
spec:
  ports:
  - name: challenge
    port: 5000
    protocol: TCP
    targetPort: 5000
  selector:
    app: neural-corp3
  type: NodePort
