apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: turing-incomplete64
    tier: challenge
  name: turing-incomplete64
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: turing-incomplete64
  template:
    metadata:
      annotations:
        apparmor.security.beta.kubernetes.io/defaultProfileName: runtime/default
      labels:
        app: turing-incomplete64
        networkpolicy: allow_egress
        tier: challenge
    spec:
      automountServiceAccountToken: false
      containers:
      - env: []
        image: us-west1-docker.pkg.dev/bsides-sf-ctf-2024/challenges/turing-incomplete64:20240502-211507
        name: turing-incomplete64
        ports:
        - containerPort: 1954
          protocol: TCP
        resources:
          limits:
            cpu: '1'
            memory: 1Gi
          requests:
            cpu: 50m
            memory: 32Mi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            add: []
          runAsNonRoot: true
        volumeMounts: []
      enableServiceLinks: false
      securityContext:
        seccompProfile:
          type: RuntimeDefault
      volumes: []
