apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: match-two
    tier: challenge
  name: match-two
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: match-two
  template:
    metadata:
      annotations:
        apparmor.security.beta.kubernetes.io/defaultProfileName: runtime/default
      labels:
        app: match-two
        networkpolicy: allow_egress
        tier: challenge
    spec:
      automountServiceAccountToken: false
      containers:
      - env: []
        image: us-west1-docker.pkg.dev/bsides-sf-ctf-2024/challenges/match-two:20240501-053258
        name: match-two
        ports:
        - containerPort: 8000
          protocol: TCP
        resources:
          limits:
            cpu: '1'
            memory: 1Gi
          requests:
            cpu: 50m
            memory: 32Mi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            add: []
          runAsNonRoot: true
        volumeMounts: []
      enableServiceLinks: false
      securityContext:
        seccompProfile:
          type: RuntimeDefault
      volumes: []
