apiVersion: v1
kind: Service
metadata:
  labels:
    app: color-picker
  name: color-picker
  namespace: default
spec:
  ports:
  - name: challenge
    port: 8000
    protocol: TCP
    targetPort: 8000
  selector:
    app: color-picker
  type: NodePort
