apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: neural-corp1
    tier: challenge
  name: neural-corp1
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: neural-corp1
  template:
    metadata:
      annotations:
        apparmor.security.beta.kubernetes.io/defaultProfileName: runtime/default
      labels:
        app: neural-corp1
        networkpolicy: allow_egress
        tier: challenge
    spec:
      automountServiceAccountToken: false
      containers:
      - env: []
        image: us-west1-docker.pkg.dev/bsides-sf-ctf-2024/challenges/neural-corp1:20240504-045101
        name: neural-corp1
        ports:
        - containerPort: 5000
          protocol: TCP
        resources:
          limits:
            cpu: '1'
            memory: 1Gi
          requests:
            cpu: 50m
            memory: 32Mi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            add: []
          runAsNonRoot: true
        volumeMounts: []
      - env:
        - name: DEBUG
          value: 'true'
        - name: COOKIES
          value: session=.eJwtjjtuAzEMBe-i2oVISqLoyyzEHxIYSIBduzJ896hIOe9NMe9y5BnXV7k_z1fcyvHt5V6APCuG9zWbdLDOZG0kK0uFNXmzVo202TG9CkXnmTCHs9fhuH-JzNQByTA5MZYjNx4qKwBkLgI0crQqxgOzpYW3QPfttrJDXlec_zUb7TrzeP4-4mcPalpFgYYgdaQlbEtFkzrk4N0MPmg1LJ8__Uw_lQ.Zi2QXQ.AXRjeBq0Eh5YdBsduyOlGu4rXI0;URL=https://neural-corp1-362a0c08.challenges.bsidessf.net/admin-panel;httpOnly;Secure;SameSite=None
        - name: TARGET_URIS
          value: https://neural-corp1-362a0c08.challenges.bsidessf.net/admin-panel
        - name: PORT
          value: '3000'
        image: us-west1-docker.pkg.dev/bsides-sf-ctf-2024/challenges/webbot:latest
        name: webbot
        resources:
          limits:
            cpu: '1'
            memory: 512Mi
          requests:
            cpu: 80m
            memory: 128Mi
        securityContext:
          capabilities:
            add:
            - SYS_ADMIN
      enableServiceLinks: false
      securityContext:
        seccompProfile:
          type: RuntimeDefault
      volumes: []
