apiVersion: v1
kind: Service
metadata:
  labels:
    app: match-one
  name: match-one
  namespace: default
spec:
  ports:
  - name: challenge
    port: 8000
    protocol: TCP
    targetPort: 8000
  selector:
    app: match-one
  type: NodePort
