apiVersion: v1
kind: Service
metadata:
  labels:
    app: cwa2
  name: cwa2
  namespace: default
spec:
  ports:
  - name: challenge
    port: 5432
    protocol: TCP
    targetPort: 5432
  selector:
    app: cwa2
  type: NodePort
