apiVersion: v1
kind: Service
metadata:
  labels:
    app: web-tutorial-2
  name: web-tutorial-2
  namespace: default
spec:
  ports:
  - name: challenge
    port: 8000
    protocol: TCP
    targetPort: 8000
  selector:
    app: web-tutorial-2
  type: NodePort
